raycast: main.C scene_parser.o object3d.o matrix.o image.o orthocamera.o group.o sphere.o object3d.o
	g++ $^ -o $@

scene_parser.o: scene_parser.C
	g++ -c $< -o $@

object3d: object3d.C
	g++ -c $< -o $@

matrix.o: matrix.C
	g++ -c $< -o $@

image.o: image.C
	g++ -c $< -o $@

orthocamera.o: orthocamera.C
	g++ -c $< -o $@

group.o: group.C
	g++ -c $< -o $@

sphere.o: sphere.C
	g++ -c $< -o $@

object3d.o: object3d.C
	g++ -c $< -o $@